services:
  db:
    image: postgres:16
    container_name: vehicle-tracking_db
    restart: always
    ports:
      - "9042:9042"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGPORT: ${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vehicle_network

  server:
    build: ./server
    container_name: vehicle-tracking_backend
    ports:
      - "9040:9040"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - CLIENT_URL=http://localhost:9041
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - vehicle_network

  client:
    build: ./client
    container_name: vehicle-tracking_frontend
    ports:
      - "9041:9041"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - vehicle_network

volumes:
  pgdata:

networks:
  vehicle_network:
    driver: bridge
