version: "3.9"

services:
  db:
    image: postgres:16
    container_name: vehicle-tracking_db
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - vehicle_network

  server:
    build: ./server
    container_name: vehicle-tracking_backend
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - CLIENT_URL=http://localhost:3000
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - vehicle_network

  client:
    build: ./client
    container_name: vehicle-tracking_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - VITE_SOCKET_URL=http://localhost:5000
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - vehicle_network

volumes:
  pgdata:

networks:
  vehicle_network:
    driver: bridge
